#!/bin/bash --norc

PATH="external/com_arm_developer_toolchain_gcc_5_4/lib/gcc/arm-none-eabi/5.4.1:$PATH" \
    exec \
    external/com_arm_developer_toolchain_gcc_5_4/bin/arm-none-eabi-gcc \
    "$@"
